DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS game;
DROP TABLE IF EXISTS play;
DROP TABLE IF EXISTS post;

CREATE TABLE user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE game (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ended TIMESTAMP,
    day INTEGER NOT NULL DEFAULT 0,
    time INTEGER NOT NULL DEFAULT 0,
    humans INTEGER NOT NULL DEFAULT 0,
    wolves INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE play (
    user_id INTEGER NOT NULL,
    game_id INTEGER NOT NULL,
    name TEXT NOT NULL,
    role INTEGER,
    PRIMARY KEY (user_id, game_id),
    FOREIGN KEY (user_id) REFERENCES user (id),
    FOREIGN KEY (game_id) REFERENCES game (id)
);

CREATE TABLE post (
    game_id INTEGER NOT NULL,
    day INTEGER NOT NULL,
    number INTEGER NOT NULL,
    author_id INTEGER NOT NULL,
    body TEXT NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (game_id) REFERENCES game (id)
    FOREIGN KEY (author_id) REFERENCES user (id)
);

